### ISSUE TITLE
Broken Links to Documentation

### ISSUE THREAD

**Issue by alec-hs** [DefGuard/defguard#210]
**Describe the bug**
When using the click for more info on settings and then clicking the docs link you get redirected to your instance rather than the docs.

**To Reproduce**
1. Go to .../admin/settings
2. Click the "i" next to any settings
3. Click the "Read more in docs..." 
4. See error - you are directed to https://instance.domain.com/admin/defguard.gitbook.io

**Expected behavior**
The link should open a new tab to https://defguard.gitbook.io - preferably to the relevant section.

**Version information**
- Defguard Core version: latest
- Edge Latest

**Screenshots**
![image](https://github.com/DefGuard/defguard/assets/6503411/f7c251e0-d55d-4938-a336-118d6a99a91b)

**Comment by filipslezaklab** [comment]
For now, it will lead to the base documentation link. We will change it into a proper section link when the docs will be up to date.
