### ISSUE TITLE
Debug Info

### ISSUE THREAD

**Issue by alec-hs** [DefGuard/defguard#211]
**Is your feature request related to a problem? Please describe.**
A way to quickly see version of app and other useful info when reporting bugs etc. 

**Describe the solution you'd like**
A section in settings to show useful info like version, os, env variables (secrets not included or ** out).  

**Describe alternatives you've considered**
The side bar displaying the current version is good but more info would be great.

**Comment by teon** [comment]
I agree - this would be great to have, but with the current backlog packed with two major features I will include this not in the current release but the next one.

**Comment by teon** [comment]
We've implemented that feature: https://defguard.gitbook.io/defguard/help/sending-support-info
