### ISSUE TITLE
Username Special Chars

### ISSUE THREAD

**Issue by alec-hs** [DefGuard/defguard#212]
**Is your feature request related to a problem? Please describe.**
Username chars are very limited and restricted. 

**Describe the solution you'd like**
Ability to use special chars in usernames where possible - for example @ or - 
Some users may want their email to be their username. Using valid email regex might be an option https://regexr.com/3e48o

**Comment by filipslezaklab** [comment]
Because we support sync with LDAP, the username field is currently restricted to a simple set of characters plus numbers.
We will explore possible solutions to fix this issue in the future.

**Comment by alec-hs** [comment]
That's fair enough but LDAP's reserved chars are only the below to my knowledge, dashes and @ are supported.

``` " / \ [ ] : ; | = , + * ? < > ```

**Comment by eblet** [comment]
wow! this is relevant for me!
our logins are indicated as first.last, and it is impossible to use our logins for sso

**Comment by teon** [comment]
The problem with special chars we have is that we also support synchronisation with LDAP which has some restrictions on the login chars.

But we'll take this on the workshop and see which chars are supported by LDAP protocol and implement them.
@moubctez any comments?

**Comment by teon** [comment]
Username: zenek34 - error: user already exists.
Username: zenekXXX___ - error: user already exists.

**Comment by BhuviTheDataGuy** [comment]
+1 for this feature.

Most of the mid-size orgs, they use SSO Auth, or email based access grants. Some level of separation between first name and last name in the username will be a great feature.

**Comment by teon** [comment]
Adding a new user works, **but when I want to login**: `No special characters are allowed.` error in the username field
