### ISSUE TITLE
YubiBridge package

### ISSUE THREAD

**Issue by kchudy** [DefGuard/defguard#285]
Analogicznie jak gateway - DEB i RPM oraz SYSTEMD.

Kryteria Akceptacji:

* są pakiety w release
* w dokumentacji na stronie ([[defguard.gitbook.io](http://defguard.gitbook.io/)|http://defguard.gitbook.io]/) jest informacja nt. pakietów
* w readme jest info nt. pakietów

**Comment by teon** [comment]
Closing since we have new: https://github.com/DefGuard/YubiKey-Provision
