### ISSUE TITLE
One line install

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#306]
## goal

export DEFGUARD_DOMAIN=xyz.com
export DEFGUARD_VPN_NAME=....
export DEFGUARD_VPN_IP...
export DEFGUARD_ENROLMENT... # jest to jest enrollment nie ma to nie ma
export DEFGUARD_HTTPS=true # CADDY - nie ma to nie ma

curl -fsSL https://get.defguard.net | bash

## result

- deployed by docker-compose defguard full stack (proxy, core, gateway)
- automatic deployment of proxy + LE SSL (caddy?)
- print URL, login, pass.... to user
- one line install to Docs & README

**Comment by teon** [comment]
@wojcik91 please add to main readme and to documentation: https://defguard.gitbook.io/defguard/features/setting-up-your-instance as main installation process + description of the whole script, env vars etc

**Comment by wojcik91** [comment]
@teon I updated the main readme and extracted the gitbook docs into a dedicated page
