### ISSUE TITLE
Unable to setup OIDC login for min.io

### ISSUE THREAD

**Issue by j-chmielewski** [DefGuard/defguard#330]
**Describe the bug**
OIDC login for min.io service via Defguard doesn't work. Error message:
```
Error from IDP
An error occurred, please try again
Invalid kid value <nil>
```

**To Reproduce**

1. In defguard add OIDC client for min.io.
Redirect URL 1: `https://my-minio-instance.com/oauth_callback`
Scopes: `openid,profile,email`

2. In min.io instance setup Defguard OIDC provider.

Go to `Administrator -> Identity -> OpenID -> Create Configuration`
Fill in the form:
![image](https://github.com/DefGuard/defguard/assets/921741/d25d28a0-905b-43ea-ab88-81ef68e7047a)
Save and restart min.io server.

**Expected behavior**
Expected to be able to log into min.io service via Defguard OIDC. Instead the error is displayed after the OIDC flow:
![image](https://github.com/DefGuard/defguard/assets/921741/625d3ead-2ed2-4242-a291-8b29df6f6453)

**Version information**
- Defguard Core version: v0.7.0

**Additional context**
Possible reasons:
* min.io seems to require JWKS key rotation mechanism for OIDC while Defguard does not return kid with JWT token
* Defguard instance does not manage the keys as required. The `/api/v1/oauth/discovery/keys` endpoint returns emtpy key set:
```
{
	"keys": []
}
```

**Comment by teon** [comment]
https://defguard.gitbook.io/defguard/features/openid-connect/minio
