### ISSUE TITLE
Add LDAP configuration in the Settings Tab ("LDAP")

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#388]
Righ now LDAP sync config is by ENV VARS, but with 0.7 we have started to extend the Settings with tabs (now general & SMTP). LDAP should be next. One **additional thing should be to _test_ the LDAP connection** (precisely the same as SMTP).

**Comment by teon** [comment]
To move forward please check this on our production.

**Comment by dzania** [comment]
@teon Configured ldap settings on our production and test button returns `Ldap connected successfully`
