### ISSUE TITLE
Prepare a solution in the docs for authenticating SSH connections with keys from Defguard

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#398]
Please describe in docs how to use SSH auth with keys from defguard, few examples:
1. With LDAP
2. With a small client that will connect to API and get the key

**Comment by wojcik91** [comment]
For now we'll add a public API endpoint that can be used with `sshd` `AuthorizedKeysCommand` to fetch public keys.
For now we only store one key per user (when Yubikey is provisioned) but in the future we'll add more, so the endpoint and the example command to use on server should already be prepared to handle multiple keys.

**Comment by wojcik91** [comment]
Docs available here: https://defguard.gitbook.io/defguard/features/ssh-authentication
