### ISSUE TITLE
Can't use .well-known/openid-configuration from Vault

### ISSUE THREAD

**Issue by orlovmyk** [DefGuard/defguard#403]
https://github.com/DefGuard/defguard/blob/1f62627841cc00093393f51ed62b8757406f5e4a/src/handlers/openid_flow.rs#L790

Trying to connect Vault to Defguard as OIDC IdP, so in defguard logs
```
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server] GET /.well-known/openid-configuration text/html:
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server::_] Matched: (FileServer: ./web/dist) GET /<path..> [3]
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server::_] Outcome: Forward
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server::_] Matched: (smart_index) GET /<path..> [4]
defguard-core-1     | [2023-11-11 21:06:46.534][WARN][defguard::_] Parameter guard `path: PathBuf` is forwarding: BadStart('.').
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server::_] Outcome: Forward
defguard-core-1     | [2023-11-11 21:06:46.534][ERROR][rocket::server::_] No matching routes for GET /.well-known/openid-configuration text/html.
defguard-core-1     | [2023-11-11 21:06:46.534][WARN][rocket::server::_] No 404 catcher registered. Using Rocket default.
defguard-core-1     | [2023-11-11 21:06:46.534][INFO][rocket::server::_] Response succeeded.
```

while when trying to save it in Vault

<img width="756" alt="image" src="https://github.com/DefGuard/defguard/assets/29892471/2a665457-90eb-43d1-9288-c44aa4985fcc">

Vault logs
```
vault  | 2023-11-11T21:10:01.483Z [ERROR] auth.oidc.auth_oidc_55242a6f: error checking oidc discovery URL:
vault  |   error=
vault  |   | error creating provider with given values: NewProvider: unable to create provider: 404 Not Found: <!DOCTYPE html>
vault  |   | <html lang="en">
vault  |   | <head>
vault  |   |     <meta charset="utf-8">
vault  |   |     <title>404 Not Found</title>
vault  |   | </head>
vault  |   | <body align="center">
vault  |   |     <div role="main" align="center">
vault  |   |         <h1>404: Not Found</h1>
vault  |   |         <p>The requested resource could not be found.</p>
vault  |   |         <hr />
vault  |   |     </div>
vault  |   |     <div role="contentinfo" align="center">
vault  |   |         <small>Rocket</small>
vault  |   |     </div>
vault  |   | </body>
vault  |   | </html>
vault  |
```

Looks like it's an issue with MIME types, I don't have any workaround for now

**Comment by orlovmyk** [comment]
Nevermind, I succeed to create provider. OIDC discovery url should be set without '.well-known/openid-configuration'
<img width="589" alt="image" src="https://github.com/DefGuard/defguard/assets/29892471/396ec931-78d3-4750-95d0-f8d4752c448e">

Anyways what do you think about responding to `text/html` requests too?

**Comment by teon** [comment]
Oh that's great! Could you write a quick comment on how to configure Vault with defguard? We would add it then to the documentation. Thank you kindly!

**Comment by orlov-m** [comment]
@teon sure, I will do a PR

Can you answer this too 🥺 🙏 ?
> Anyways what do you think about responding to text/html requests too? It took me several hours to realize that Rocket doesn't respond to 'text/html' requests on '.well-known/openid-configuration'

**Comment by orlovmyk** [comment]
@teon sure I will do a PR

Also can you answer please on this?
> Anyways what do you think about responding to text/html requests too? It took me several hours to realize that Rocket doesn't respond to 'text/html' requests on '.well-known/openid-configuration'

**Comment by orlovmyk** [comment]
@teon added docs PR https://github.com/DefGuard/docs/pull/14
