### ISSUE TITLE
Possibility to manage SSH/GPG/YK keys

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#415]
Right now keys are just added during YK provisioning, we need functionality to add/remove keys manually.

**Comment by wojcik91** [comment]
Remember to update `ssh_authorized_keys` endpoint

**Comment by blazej-teonite** [comment]
Adding SSH and GPG keys: https://github.com/DefGuard/defguard/pull/521

TODO:
Implement YubiKey changes
Create hardware keys table
Add relation to authentication key table
