### ISSUE TITLE
Webhook token issue with ntfy.sh

### ISSUE THREAD

**Issue by wojcik91** [DefGuard/defguard#433]
From user submission on Matrix:
Hi there! 

Questions about webhooks. I am using [ntfy.sh](http://ntfy.sh/), however the api tokens it creates appear to always be lowercase. Hence I get the "One uppercase character required." message. Any tricks to make it work? 

[ntfy.sh](http://ntfy.sh/) just creates: "Authorization: Bearer tk_xf46ugp45ow7xz8nv657nvhidxh3m" for example.

**Comment by teon** [comment]
We need to:
1. Change get -> POST
2. Add upper case in token generation
