### ISSUE TITLE
2FA for Wireguard

### ISSUE THREAD

**Issue by zaucker** [DefGuard/defguard#466]
**Is your feature request related to a problem? Please describe.**
One of our clients has a requirement by some of her (biggest) customers to use 2FA for their VPN tunnels from the home office into the company site. We currently use Wireguard. Although it might be questionable that 2FA makes all that much sense as security improvement in this context, at least it would prevent sharing a Wireguard access with other people (or make it more difficult).

Right now this is a blocker for us suggesting defguard to our client as a general authentication/security system.

**Describe the solution you'd like**
May be integration of [WAG](https://github.com/NHAS/wag) would be an option? 

**Describe alternatives you've considered**
As Wireguard is an integral part of defguard, it seems there is no real sensible alternative than integration of 2FA.

**Comment by teon** [comment]
Hi @zaucker - thank you for your feedback.

We have extensive requests from various companies and individuals about implementing MFA in the client - so this will be **our priority for next release**

We have some ideas on how to implement it - but thank you for your findings in terms of WAG - we will look into their approach as well.

We would appreciate any feedback - maybe you could join our Matrix and give us more thoughts, ideas, requests?

Kind regards, Robert

**Comment by teon** [comment]
@zaucker and here it is! MFA even! As promised here are details: https://defguard.gitbook.io/defguard/help/desktop-client/architecture - checkout new releases!

**Comment by zaucker** [comment]
Hi Robert,
very nice that defguard now has MFA for Wireguard. We are going to make a test installation for our company network and then present it to our customer.
There is one problem we see, however, at least for our customer. One of their customers requires them to have **ALL** VPN connections 2FA authenticated, including those from mobile devices. If we understand your implementation correctly, your current solution doesn't support this as on mobile devices we cannot use the defguard client.
Or am I missing something?
If we are correct with our assessment, are there any plans for a mobile client or another 2FA wireguard implementation within  defguard for that purpose?
Thanks,
Fritz
