### ISSUE TITLE
Docs for REST API

### ISSUE THREAD

**Issue by eblet** [DefGuard/defguard#480]
where docs for defg api? :D

**Comment by eblet** [comment]
hi!
I'm raising a question about API documentation
I have a question

- how to create/block a user in Defguard via API?
we are making a service for internal use within the company, and we want to manage DG users through our service

**Comment by eblet** [comment]
@teon

**Comment by teon** [comment]
@eblet For now we don't have any user "disabling" - I have added it to backlog - you can follow the issue:
https://github.com/DefGuard/defguard/issues/556
for now if you want to disable a user the simplest "hack" is to change it's password
API docs are on backlog as well - but too much to be done..

**Comment by teon** [comment]
Summing up - we need API documentation - best would be to:
- [ ] automatically generate them using Rust Doc mechanisms
- [ ] would be great to prepare a GitHub Actions pipeline that will produce artefacts and publish them (we could use github pages to publish then on: https://docs.defguard.net for example).

**Comment by teon** [comment]
Done in upcomming 1.0.0
