### ISSUE TITLE
Error Version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by eblet** [DefGuard/defguard#488]
**Describe the bug**
After install defg with parameters, get error logs on docker container **ghcr.io/defguard/gateway:lates**

> /usr/local/bin/defguard-gateway: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/defguard-gateway)

**To Reproduce**
- Install from one-click script with use parameters
- Enter defguard domain [default: ]: sub.domain.com
- Enter enrollment domain [default: ]: 
- Use HTTPS [default: false]: false

- Enter VPN location name [default: ]: office
- Enter VPN server address and subnet (e.g. 10.0.60.1/24) [default: ] {ip range}
- Enter VPN gateway public IP [default: ]: {ip}
- Enter VPN gateway public port [default: ]: {port}

**Version information**
- Defguard Core version: latest from one-click install

**Comment by eblet** [comment]
fixed, my server is alredy pull all containers, and been their conflict
thnx, and sorry!

**Comment by eblet** [comment]
nope, problem is here D:

> 79d7376cd276   ghcr.io/defguard/gateway:latest    "/usr/local/bin/defg…"   About an hour ago   Restarting (1) 2 seconds ago   

> /usr/local/bin/defguard-gateway: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/defguard-gateway)

**Comment by wojcik91** [comment]
Hi.
Thanks for alerting us to the issue. 
There was indeed a problem with the default Debian version in new `rust` image. 
We fixed it and published new images.
