### ISSUE TITLE
Error: Failed to initialize first VPN location. A location already exists.

### ISSUE THREAD

**Issue by scott-mackenzie** [DefGuard/defguard#527]
**Describe the bug**
Error: Failed to initialize first VPN location. A location already exists.

**To Reproduce**
1. Use One-line install script
2. Log into your portainer interface
3. Check logs on container "[root-core-run-3841c11c87ec]"
4. See Error: "Error: Failed to initialize first VPN location. A location already exists."

**Expected behavior**
The container assigned to the root-core-run is not stable and rebooting or rebuilding does nothing to make the container stable. Should this be a run once and this could be ignored or should this container always be running?

**Version information**
- Defguard Core version: latest:stable
- Defguard Gateway version: latest:stable
- Operating system and version running the gateway: Ubuntu 22.04 base running docker
- Your browser and version Firefox, Chrome, etc all same.

**Logging Output**
Error: Failed to initialize first VPN location. A location already exists.
Error: Failed to initialize first VPN location. A location already exists.
Error: Failed to initialize first VPN location. A location already exists.

**Comment by scott-mackenzie** [comment]
Additional error logged upon forced "restart" of container:

thread 'main' panicked at /build/src/db/mod.rs:17:10:
Database connection failed: Io(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by teon** [comment]
Thank you for the issue, we have another support issue with the same error on ubuntu 22.04 - we need to double check and get back to you.

**Comment by teon** [comment]
I've just installed a clean VM with latest ubuntu 22.04.3 LTS - clean install and tested on docker from distro packages, no problems with one-line-install.
So there must be something specific for your installation. Could you confirm:
- ubuntu version - result of the following command: lsb_release -a
- docker version -  result of the following command: docker --version
- docker-compose version -  result of the following command: docker-compose -v
- please provide how are you configuring defguard - if you can all the configuration: domains, IPs, ports - all so we can replicate - best would be to paste all the output from one line install
- can you also attach a "test.log" which is the result of the following command: docker-compose logs | tee test.log

Getting all that should help us to figure out what is specific about your setup that it "brakes".

Thank you.

**Comment by teon** [comment]
Closing for now. If you will provide all the details above, you can reopen the issue.
