### ISSUE TITLE
defguard gateway configuration issue

### ISSUE THREAD

**Issue by TokuiNico** [DefGuard/defguard#532]
**Version information**
- Defguard Core version: v0.9.0
- Defguard Gateway version: v0.6.0
- Operating system and version running the gateway: Ubuntu 22.04.3 LTS

Hi, I am trying to set up defguard on aws ec2 but I encountered some problems. The current architecture is as follows:

vpc: 10.0.0.0/16
vpn network: 10.1.0.1/16
vpn allowed ips: 10.1.0.1/16,10.0.0.1/16

gateway server
- In vpc
- ip: x.x.x.x (public ip), 10.0.0.1 (vpc private ip)

core server
- In vpc
- ip: 10.0.0.2 (vpc private ip)

client
- ip: 10.1.0.2 (vpn ip)

Now the client's wireguard client can successfully connect to the vpn service, but it cannot connect to the core server (10.0.0.1:8000). If the allowed ips are set to 0.0.0.0/0, no domain names can be resolved. I would like to know if there is a problem with this architecture or if there is something wrong with the settings.

**Comment by teon** [comment]
@TokuiNico have you seen this tutorial? If you have EC2 you can configure SSL as well and not connect to core by internal IPs and ports: https://defguard.gitbook.io/defguard/tutorials/step-by-step-setting-up-a-vpn-server

**Comment by TokuiNico** [comment]
@teon  Thank you for your suggestion. I set it up successfully by following the instructions.
I also want to know if I can set up a private DNS service on the server where the core is located so that wireguard client can use it.
Will this setup cause any problems?
