### ISSUE TITLE
Admin password empty after first install attempt failed 

### ISSUE THREAD

**Issue by aleex1848** [DefGuard/defguard#537]
-Installed fresh Ubuntu 22.04.

-installed docker [using docker repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)

-tried `sudo curl --proto '=https' --tlsv1.2 -sSf -L https://raw.githubusercontent.com/DefGuard/deployment/main/docker-compose/setup.sh -O && bash setup.sh`

-failed with `ERROR: failed to create VPN network`

-switched to root using `sudo -s`

-tried again acting as root `curl --proto '=https' --tlsv1.2 -sSf -L https://raw.githubusercontent.com/DefGuard/deployment/main/docker-compose/setup.sh -O && bash setup.sh`

-setup finishes but password is empty so no login possible:
![image](https://github.com/DefGuard/defguard/assets/17452861/00b99d45-ef4d-4c02-b0c2-657e37fd23b1)

**Comment by aleex1848** [comment]
The password is being set correctly and can be found inside the .env file. It's only not shown in the setup-finished-ouput

**Comment by teon** [comment]
Fixed in deployment
