### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by zvana** [DefGuard/defguard#550]
You can set an email with whitespace before the text and it doesn't alert you for incorrect format neigher it's not trimmed. When you try to send the enrollment email, it's not sent to the correct email. So it should at least check it or ideally trimm it. It can also report if the email can't be delivered due to invalid email address.

**Comment by teon** [comment]
@filipslezaklab you're rewriting forms in new release - please double check this bug.

**Comment by teon** [comment]
@filipslezaklab still not fixed:

<img width="1013" alt="Screenshot 2024-02-28 at 11 10 08" src="https://github.com/DefGuard/defguard/assets/139682/9c2304da-5b72-4b7d-8668-d72f9ab82398">

**Comment by filipslezaklab** [comment]
@teon It's trimmed now on submission. It was easier to just trim all strings rather than implementing new validators on each form.

**Comment by teon** [comment]
Implement either default ZOD validator, or connect isEmail from 'validation' lib
