### ISSUE TITLE
MFA Code Email reformat

### ISSUE THREAD

**Issue by 4lb** [DefGuard/defguard#555]
Currently, emails send small, bolded code, which is hard to spot and easy to mis-click. Let's provide a bigger code font, separated from the rest, to easily identify and copy.
design in figma -> 
https://www.figma.com/file/uoFcgpOuVWa6g7tvKwB52o/defguard-01?type=design&node-id=6961-3760&mode=design&t=YByQ5UX73Ce469vD-4

**Comment by cpprian** [comment]
- [ ] Add link in the enrollment email to this download page

**Comment by teon** [comment]
@cpprian niestety nie ma na dev - jak mam przetestowac?

**Comment by t-aleksander** [comment]
There was some issue with our deployment action (probably on github's side), I've reran it and it should deploy when the e2e tests finish
