### ISSUE TITLE
Limit how many devices users are permitted to have

### ISSUE THREAD

**Issue by SkullKill** [DefGuard/defguard#566]
**Is your feature request related to a problem? Please describe.**
Admins have no control on what device, and how many devices the user deploy the vpn clients to.

**Describe the solution you'd like**
We would like to have the option to disable the option for the user to provision their own VPN (both defguard and native wireguard).

So , an option to completely disable the "Add a new device" option for users. And only allow the Admins to generate a token for the user to use to provision their defguard clients.

**Comment by teon** [comment]
Related to: https://github.com/DefGuard/defguard/issues/609

**Comment by teon** [comment]
Done - releasing in 1.0
