### ISSUE TITLE
Not possible to add more than 2 subnets in allowed ips

### ISSUE THREAD

**Issue by orlovmyk** [DefGuard/defguard#568]
**Describe the bug**
Not possible to add more than 2 subnets in allowed ips. Meanwhile nothing stops users to add as many subnets as possible. While it's working just fine, from UI it's saying you can't add allowed ips.

**To Reproduce**
1. Go to defguard UI
2. Click on "Edit Location Settings" or "Create new location"
3. Click on "Add new location"
4. Choose "Manual Configuration"
5. In Allowed IPs try to add more than 2 subnets, e.g. `10.12.0.0/16, 10.30.0.0/16, 10.99.0.0/16`

**Expected behavior**
IPs are added and used in config generation

**Version information**
- Defguard Core version: v0.9.0
- Operating system and version running the gateway: k8s helm chart
- Your browser and version: firefox 101.0.1

**Screenshots**

<img width="921" alt="Screenshot 2024-02-20 at 20 12 33" src="https://github.com/DefGuard/defguard/assets/29892471/a03311d6-dc9f-49bf-9b6e-f4bb507778f0">
<img width="933" alt="Screenshot 2024-02-20 at 20 12 39" src="https://github.com/DefGuard/defguard/assets/29892471/119db2f2-9f25-461a-9819-27e56a28de64">

**Additional context**
Workaround for now, aks users to add IPs on their own

**Comment by teon** [comment]
Fixed
