### ISSUE TITLE
Session is required, error on login

### ISSUE THREAD

**Issue by Zekhap** [DefGuard/defguard#588]
**Describe the bug**

**To Reproduce**
1. Install on portainer with compose
2. Start

I have cookie insecure to true.
I can access the login page but i cannot login.
Tried to fix for 8 hours but failed.

**Expected behavior**
Basically install & start and be able to login.

**Version information**
- Defguard Core version: v0.9.0
 - Your browser and version [brave 1.63.174]

**Screenshots**
![Screenshot 2024-03-16 001803](https://github.com/DefGuard/defguard/assets/2479166/b5abf4f2-3aad-4c69-bd0b-99e6dbbabed1)

**Additional context**

I have Proxmox that have a container with Portainer.
Tailscale is installed on Proxmox shell.
But also inside Portainer as a stack.
Im accessing the login page with tailscale ip.

**Comment by William-Mou** [comment]
Hello @Zekhap 
How did you solve this issue? I'm also running a VM inside PVE and currently facing the same problem.
