### ISSUE TITLE
Gateway reports as offline

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#597]
**Describe the bug**
We have two gateways. And after some time in the defguard admin panel, these gateways are showed as offline

**To Reproduce**
1. Setup new gateway
2. Register to Defguard
3. Wait 24hours.

**Expected behavior**
Gateways are showed online.

**Version information**
- Defguard Core version: v0.9.0
- Defguard Gateway version: v0.6.2 
  - Operating system and version running the gateway: Ubuntu 22.04

**Screenshots**
<img width="984" alt="image" src="https://github.com/DefGuard/defguard/assets/98015934/e3fec763-4a73-4051-ae55-072c3eb6678a">

**Comment by t4ov** [comment]
Defguard gateway say it requires core 0.9.2. But where to get it?
<img width="670" alt="image" src="https://github.com/DefGuard/defguard/assets/98015934/bca95653-39a8-49eb-a6e4-4316866a2cfd">

Last release is v0.9.0 of Core.

**Comment by teon** [comment]
This is a pre-release - and waiting for core 0.9.1 which is not out yet..
Please install 0.6.1 and all should be ok.

We will skip 0.9.1 - during development we've decided to release 0.10 (probably on Monday / Tuesday next week).

**Comment by t4ov** [comment]
Ahh, ok. I guess i will wait for 0.10 and update both at once.

**Comment by t4ov** [comment]
After upgrade to 0.10.0, all gateways are displayed online. Thanks.
