### ISSUE TITLE
Couldn't retrieve gateway configuration error spammed

### ISSUE THREAD

**Issue by francois-pasquier** [DefGuard/defguard#599]
My logs are getting spammed by this:

```
defguard-gateway  | [2024-03-24T22:56:22Z ERROR defguard_gateway::gateway] Couldn't retrieve gateway configuration, retrying: status: Unavailable, message: "error trying to connect: received corrupt message of type InvalidContentType", details: [], metadata: MetadataMap { headers: {} }
```

wireguard is not working

I already filled an issue there https://github.com/DefGuard/gateway/issues/75 but it doesn't seem to be checked.

Simply following the instructions there https://defguard.gitbook.io/defguard/tutorials/step-by-step-setting-up-a-vpn-server are enough to reproduce the issue.

I can also reproduce it on a brand new debian VM.

**Comment by teon** [comment]
Hi there, please follow this guide for posting support type issues: https://defguard.gitbook.io/defguard/contact-us/support#still-not-working-help

**Comment by teon** [comment]
Closing, please provide all necessary data and reopen.
