### ISSUE TITLE
sample URL shown in the web UI for Docker based gateway setup has wrong protocol

### ISSUE THREAD

**Issue by dbutti** [DefGuard/defguard#603]
**Describe the bug**
The sample command shown when editing a location in the GUI for Docker based gateway setup wrongly uses http as protocol scheme for the DEFGUARD_GRPC_URL. It should be HTTPS to avoid confusion.

**To Reproduce**
1. Go to "Edit location" in the GUI and look for the gateway server setup
**Expected behavior**
The GRPC should be shown with https:// at the beginning. Even better, we could show the real IP address of the GRPC service (if known)

**Version information**
- Defguard Core version: v0.9.1
- Running as docker container with the official image

**Comment by teon** [comment]
We have a new design for gateway deployment in upcomming 1.0.0
