### ISSUE TITLE
Peer disconnect threshold [seconds] value is incorrect

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#615]
**Describe the bug**
Complaining that peer disconnect threshold is incorrect even if you just open location and press save without editing anything. 

**To Reproduce**
1. Go to Location configuration
2. Click Save
3. Scroll down to bottom 

**Expected behavior**

**Version information**
- Defguard Core version: v0.10.0
- Defguard Gateway version: vX.Y.Z (if bug is applicable to VPN functionality)
  - Operating system and version running the gateway: Mac OS
 - Your browser and version [e.g. chrome 99, safari]: Edge

**Screenshots**
<img width="702" alt="image" src="https://github.com/DefGuard/defguard/assets/98015934/2744dd7b-0138-4b0b-9402-335ea71671c4">

**Comment by teon** [comment]
Fixed in 0.11.0
