### ISSUE TITLE
Typo in feature listing

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#616]
**Describe the bug**
Typo in a word **beatiful**

**To Reproduce**
1. Go to https://defguard.net/
2. Scroll down 

**Expected behavior**
Should be: beautiful

**Screenshots**
<img width="803" alt="image" src="https://github.com/DefGuard/defguard/assets/98015934/42978b85-211d-427f-9cd8-7d4d99bbea1f">

**Additional context**
Not critical :)

**Comment by rapus95** [comment]
Adding to that, "dekstop" could also get a fix!
should be: desktop
