### ISSUE TITLE
OIDC client instead of server

### ISSUE THREAD

**Issue by ne0YT** [DefGuard/defguard#624]
I already have an SSO solution running and would like to integrate Wireguard with SSO into it.

**Comment by t4ov** [comment]
+1

**Comment by bmaingret** [comment]
Similar to https://github.com/DefGuard/defguard/issues/582 ?

**Comment by ne0YT** [comment]
@bmaingret yes

**Comment by teon** [comment]
Closing as a) it's implemented in upcomming 1.0.0 release and it's duplicate for our main issue: https://github.com/DefGuard/defguard/issues/602
