### ISSUE TITLE
docker compose - Database connection failed: Database(PgDatabaseError { severity: Fatal, code: "28P01", message: "password authentication failed for user "defguard""

### ISSUE THREAD

**Issue by ne0YT** [DefGuard/defguard#625]
**Describe the bug**
I try to run the:
docker-compose setup
it fails with:
```
Database connection failed: Database(PgDatabaseError { severity: Fatal, code: "28P01", message: "password authentication failed for user "defguard"", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("auth.c"), line: Some(326), routine: Some("auth_failed") })
```

**To Reproduce**
1. Setup Docker compose as written here:
https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/docker-compose
2. docker compose up

**Expected behavior**
It starts the service

**Version information**
- Defguard Core version:
https://github.com/defguard/defguard/pkgs/container/defguard/196984312?tag=latest

**Comment by LOROP-Franzi** [comment]
what for an operating system? 

With ubuntu 20.04 LTS Server it works for me, but with 22.04 and 24.04 I got the same error.

**Comment by teon** [comment]
No response, closing.
