### ISSUE TITLE
comprehensive security report not found

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#631]
File is not found.
Press on the link, 404 error

[comprehensive security report](https://defguard.net/images/decap/isec-defguard.pdf))

<img width="755" alt="image" src="https://github.com/DefGuard/defguard/assets/98015934/7c0bcf69-e2a5-4563-8ce4-80859dba4b36">

**Comment by dorianborovina** [comment]
Still the same on 16.06.2024.

**Comment by teon** [comment]
@dorianborovina @t4ov - sorry - bad link it's here: https://defguard.net/pdf/isec-defguard.pdf
