### ISSUE TITLE
Firewall for user groups

### ISSUE THREAD

**Issue by eblet** [DefGuard/defguard#633]
sup!

I have a question of this nature
firezone.dev had an internal firewall that allowed access to resources to be configured by group
for example, the Art department team had access to a limited number of servers, while the Devs department had access to others
Are you planning to implement something similar? 

Ofc, it is possible to configure everything via iptables in WireGuard, which is how it is configured now
However, it would be nice to have such functionality in Defguard web interface

**Comment by teon** [comment]
For now we are not planning to implement any firewall functionalities - we have a large backlog with more priority features. That may change in the feature.
