### ISSUE TITLE
Implement CORE & PROXY GRPC healthchecks

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#678]
Right now there is no way to check if grpc is working correctly. There is a healthcheck spec for gRPC. Here is even example code: https://github.com/hyperium/tonic/tree/master/examples/src/health for tonic.

- [x]  implement GRPC healthcheck for CORE GRPC
- [x]  implement GRPC healthcheck for PROXY GRPC
- [x] After implementation, please add to documentation information about helathhecks https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/health-check
- [x] Add to documentation examples how to check from command line (eg. curl) that proxy/core grpc is working

**Comment by teon** [comment]
Implemented in upcomming 1.0.0

**Comment by HanCheo** [comment]
@teon 
Is it only way to use the REST api?? in my case i am using aws alb with eks, and the value of health check status in alb target group should be between 0-99. but this rest api response status 200, 503. any plans to create grpc method for the health-check??
