### ISSUE TITLE
Implement new token for gateway in location

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#680]
When editing the location we have only a **docker based** setup - that was ment to be as an example but we forgot to state that. A lot of people are doing other types of deployment (from packages) and can't find the token.
Can't blame them its somwhere here:
```
docker run -e DEFGUARD_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciafsdfOiJIUzI1NiJ9.dfaseyJpc3sdfiOiJEZasdfWZHdWFyZCIsInN1YiI6IkRFRkdVQVJELU5FVFdPUkstMSIsImNsaWVudF9pZCI6IjEiLasdfaCJleHAiOjYwMTYxMTI0MTEsIm5iZiI6MTcyMTE0NTExNn0.kKEW_ouFi9h-IQMhHG8oFI-m22QmHKC5BZpnyfBuO1Y -e DEFGUARD_GRPC_URL=https://defguard-grpc-dev.teonite.net/ --restart unless-stopped --network host --cap-add NET_ADMIN ghcr.io/defguard/gateway:latest
```

This UX SUX 🗡 

What we need to do is to:

1. Have a clear visible place just to Copy just the TOKEN
2. Inform that you can deploy gateway:
- From package: install the package available at: https://github.com/DefGuard/gateway/releases/latest and configure /etc/defguard/gateway.toml
- If you are doing one line install: https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/one-line-install you don't need to do anything
- Docker - stays the same command as now

**Comment by 4lb** [comment]
design -> https://www.figma.com/design/uoFcgpOuVWa6g7tvKwB52o/defguard-01?node-id=7678-10242&t=M3kX5PGA9Q1wG4Tg-11
