### ISSUE TITLE
Traffic display abnormality problem

### ISSUE THREAD

**Issue by linuxyn** [DefGuard/defguard#725]
Why is my client already  closed, but my server page keeps showing upload and download traffic?

defguard 0.11.0
OS   ubuntu 22.04
defguard client 0.4.0 （macOS）

<img width="1785" alt="image" src="https://github.com/user-attachments/assets/bbb6a4b7-56d2-4d38-a862-20a75727a949">

In the past two days, I have been feeling that there is an abnormality in the upload and download traffic of the server page. Today I simply closed my client for half an hour, but I found that the upload and download traffic of the server page has not stopped, and Astonishingly high. I also specifically monitored the bandwidth of the server's public IP address. I found no abnormal problems with incoming and outgoing traffic. I don't know what's going on now.

**Comment by teon** [comment]
@linuxyn I think this is related with this bug that we are aware of: https://github.com/DefGuard/client/issues/194 - sometimes even one quits the client the VPN connection stays active... I will keep this open until we investigate the previous bug.

**Comment by teon** [comment]
Fixed in https://github.com/DefGuard/client/issues/194 - next wek we will release 0.5.0 desktop client with the fix - please monitor.
