### ISSUE TITLE
On branch 'dev' automatically change version to vX.Y.Z-SHACommit

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard#727]

**Comment by teon** [comment]
@moubctez let me know when it's on dev.

**Comment by t-aleksander** [comment]
Its on dev but doesn't seem to work correctly, at least with docker deployment.



![Image](https://github.com/user-attachments/assets/042254cb-1bc2-4c8e-9ed6-556b2b9bd91e)

![Image](https://github.com/user-attachments/assets/3f64bae7-4409-49b6-b8f5-0661f30fb12a)

**Comment by teon** [comment]
yap - assigning back to @moubctez
