### ISSUE TITLE
exec ./defguard: exec format error && ERROR: failed to create VPN network

### ISSUE THREAD

**Issue by alehostert** [DefGuard/defguard#728]
**Describe the bug**
One-line install script fails to execute core container:

```
 ▶ Adding VPN to core & generating gateway token...
WARN[0000] /opt/defguard/docker-compose.yaml: `version` is obsolete 
[+] Creating 1/1
 ✔ Container defguard-db-1  Recreated0.7s 
[+] Running 1/1
 ✔ Container defguard-db-1  Started0.3s  
exec ./defguard: exec format error
ERROR: failed to create VPN network
```

**To Reproduce**

Run setup.sh

**Expected behavior**

A fully functional defguard.

**Version information**
- Defguard Core version: v0.11.0
- Defguard Gateway version: v0.7.0
  - Operating system and version running the gateway: Rocky Linux 8.5 (Green Obsidian)
 - Your browser and version: Brave 1.68.134 Chromium: 127.0.6533.88 64 bits

**Screenshots**

![image](https://github.com/user-attachments/assets/a6121052-dd47-40e9-a8aa-0352e8c35174)

**Comment by teon** [comment]
@moubctez updated latest docker today - @alehostert and you are right, something is off with this image. I've tested on our testing server and we have the same error.

**Comment by teon** [comment]
@moubctez did you mix something with arm builds?
I've narrowed the error to this:
```
! core The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v1) and no specific platform was requested                         0.0s
core-1     | exec ./defguard: exec format error
```
@moubctez I know what has happened - you pushed it on your Mac ARM and that's why it's not working...
We need to re-run builds...

**Comment by teon** [comment]
@alehostert ok I've fixed the tag on the docker-latest. Should be working now. Just do 'docker compose pull'.
