### ISSUE TITLE
Failed to connect to Proxy

### ISSUE THREAD

**Issue by dadgam3er** [DefGuard/defguard#731]
**Using the one liner (setup.sh)**
Love the project by the way. I did exactly like the video tutorial and followed the documentation, even after tweaking a bit, I'm still getting this error

**core-1     | 2024-08-16T03:53:05.299839Z ERROR defguard::grpc: Failed to connect to proxy, retrying in 10s**
**core-1     | 2024-08-16T03:53:15.301828Z ERROR defguard::grpc: Failed to connect to proxy, retrying in 10s**

**Expected behavior**

**Version information**
- Defguard Core version: v0.11.0
- Ubuntu
 - chrome, Firefox

I'm using nginx proxy manager... any solution?

**Comment by teon** [comment]
Hi @dadgam3er - thank you for reaching out. Please follow instructions on what to submit here: https://defguard.gitbook.io/defguard/contact-us/support#still-not-working-help

Please also attach full docker compose logs.

When you do so, then please reopen the issue.

Robert
