### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by c8agomez** [DefGuard/defguard#733]
![error](https://github.com/user-attachments/assets/430b7ddd-9834-4e5f-98b1-bfc1df690790)
I can't retrieve the customer's saved information. when it is created for the first time there is no problem it shows it fine.  But when I want to download it again it does not show me the private key.

**Comment by teon** [comment]
@c8agomez That is by design - defguard does not store device private keys.

If you want to configure the device again you will need to add a new one.

**Comment by c8agomez** [comment]
I do not want to reconfigure from downloading the configuration again since it comes with the option. Otherwise I don't understand why it brings the option to show configuration if it doesn't work.

**Comment by teon** [comment]
@c8agomez thats a good point - we probably should disable downloading configuration again.

**Comment by c8agomez** [comment]
Ok thanks then I don't see very practical defguard for a company that has a lot of customers. I do not see either the option to generate network type clients, ie a client to put on a router. The software is very good but I do not see it practical.

**Comment by teon** [comment]
It's a security first solution. Storing all private keys for all devices in a database is very insecure.

Yes it's easy and practical - but not secure.

Why do you want vpn if you don't care about security?

**Comment by c8agomez** [comment]
Tengo un sistema openvpn web que no si puedo descargar tantas veces como quiera la configuración. El caso es que necesito montar otro servidor vpn en la misma máquina pero con defguard no me vale. La información se podría guardar de forma segura otra cosa distinta es que no lo haga. En fin por mi parte dejo el caso que veo que no me sirve ni lo veo práctico por lo que le digo. Insisto que si no se puede recuperar la información de nada sirve la opción de Show configuration. Muchas gracias por todo
