### ISSUE TITLE
Configuration on EC2

### ISSUE THREAD

**Issue by d47zm3** [DefGuard/defguard#749]
Hello

great product you have here :) But I cannot overcome simple configuration on standalone EC2 instance, that is living in public subnet in my VPC, even tho I have read https://defguard.gitbook.io/defguard/tutorials/step-by-step-setting-up-a-vpn-server 

I'm using quick setup (Docker Compose) script on brand new Ubuntu 24, but I got confused on the VPN Gateway addressing part, here's my layout:

VPC CIDR:
192.168.0.0/16
Public Subnet where EC2 is running CIDR: 192.168.0.0/20
Public IP of EC2: REDACTED (assigned by AWS)
Private IP of EC2: 192.168.11.10

Now, how should this VPN Gateway be configured so people can access Internet?

   ▷ VPN location name: VPC
   ▷ VPN address: 192.168.11.10/20 tried also example 10.22.33.1/24, same effect
   ▷ VPN gateway IP: XXX
   ▷ VPN gateway port: 50555

Security Groups and Network ACLs on AWS are open, I have disabled source/destination check for instance (so it can be NAT instance)

I have configured UFW like this
```
# NAT table rules
*nat
:POSTROUTING ACCEPT [0:0]

# Forward VPN network traffic through ens18 - Change to match you out-interface
-A POSTROUTING -s 192.168.0.0/20 -o enX0 -j MASQUERADE # tried various settings here usually CIDR for VPN address, enX0 is the only interface on EC2 (before running Docker Compose)

# don't delete the 'COMMIT' line or these nat table rules won't
# be processed
COMMIT
```

Anyone managed to run Defguard on EC2 successfully? Seems like I'm totally blocked after connecting to VPN, tried to add Allowed Locations like VPC CIDR or 0.0.0.0/0 no success. Nothing particular in logs.

**Comment by teon** [comment]
Your VPN and public networks are overlapping - and no matter what vpn tool or protocol you will use it will not work.
please use for vpn for example 10.10.44.0/24 (just random in dofferent class).

Should work then since its different clas then public ec2

**Comment by d47zm3** [comment]
Thanks, my issue was re-doing different CIDR on same setup, apparently removing Docker Compose stack and volumes didn't work, setup from scratch worked.
