### ISSUE TITLE
password for admin in /etc/defguard/core.conf is always default

### ISSUE THREAD

**Issue by sebthesaviour** [DefGuard/defguard#755]
**Describe the bug**

It seems that password in /etc/defguard/core.conf in standalone installation remains default and unchangable

**To Reproduce**
try to install standalone app from here: https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/standalone-package-based-installation 

and change password for admin.

**Expected behavior**

Editing default passwd in config should work.
Either changing it from the UX

**Comment by teon** [comment]
Thank you for pointing this out - this is rather an oversight in our documentation (which we will fix). We use default admin pass just to ,initialize' the database and admin user.

Once its set - you can change it in the admin UI.

**Comment by sebthesaviour** [comment]
@teon thanx - I'm pretty sure that I wasn't able to change it from the UX - even if I've changed it from the UX it was still working for the default pass.
However - this issue is no longer present today. Thanx for answer!
