### ISSUE TITLE
Gateway:   h2 protocol error: http2 error

### ISSUE THREAD

**Issue by prabakaran-yorosis** [DefGuard/defguard#825]
Hi ,

We are facing the below issue, while create the gateway in another VM.

ERROR defguard_gateway::gateway] Couldn't retrieve gateway configuration from the core. Using gRPC url: http://localhost:50055/. Retrying in 10s. Error: status: Unknown, message: "h2 protocol error: http2 error", details: [], metadata: MetadataMap { headers: {} }

Note: We have changed the localhost to machine IP but no luck

**Comment by prabakaran-yorosis** [comment]
[teon](https://github.com/teon)

**Comment by prabakaran-yorosis** [comment]
@teon 

Awaiting for your support

**Comment by djjm86** [comment]
Hi, 

I have the same problem

`oct. 23 16:34:52 debian-12-test defguard-gateway[479]: [2024-10-23T14:34:52Z ERROR defguard_gateway::gateway] Couldn't retrieve gateway configuration from the core. Using gRPC url: https://defguard-server.mycompany.fr:444/. Retrying in 10s. Error: status: Unimplemented, message: "", details: [], metadata: MetadataMap { headers: {"server": "nginx/1.22.1", "date": "Wed, 23 Oct 2024 14:34:52 GMT", "content-type": "application/grpc", "content-length": "0"} }
`

Thanks for you're help

**Comment by teon** [comment]
@djjm86 Seems that you have an invalid NGINX configuration and core can't contact gateway under that URL.
Please check your nginx logs

**Comment by prabakaran-yorosis** [comment]
> @prabakaran-yorosis from what I understood you have core on one VM and gateway on another. So you can’t use grpc url as local host - you need to use the core VM IP address.

@teon   We tried that also, but same issue.

**Comment by prabakaran-yorosis** [comment]
@teon  We tried with core server IP address, but same issue
