### ISSUE TITLE
[QUESTION] About API Request Authentication and WireGuard User Management

### ISSUE THREAD

**Issue by velrino** [DefGuard/defguard#827]
First all, CONGRATULATIONS on this amazing tool! 😊

I'm exploring the possibility of using it in a project.

In my case, I'm developing a API that manages my users, and now I also need to manage the WireGuard connections for these users.

My goal is to use the DefGuard API to handle the communication with WireGuard.

1. I would like to know if there are any examples or documentation available regarding how to create DefGuard API Authentication (use JWT?) for use DefGuard API.

2. Could you provide information on how to create and remove WireGuard users through the API, and whether it's possible to retrieve the WireGuard configuration file (CONFIG) for these users?

Thank you in advance for your assistance.

**Comment by teon** [comment]
Hi @velrino - we plan to prepare full API (or oauth tokens to our endpoints and token management) as the API is generally there.
But that will be some time in the feature.
You can use the api with some hacks - reach out to our: support@defguard.net for unofficial docs on that.
