### ISSUE TITLE
Can't install using one-line script: failed to create VPN network

### ISSUE THREAD

**Issue by federicochiesa** [DefGuard/defguard#832]
**Describe the bug**
I'm trying to install Defguard on an Ubuntu 22.04 host using the one-line script. I go through the setup and input the correct values for our domain and network and it gives the following error:
```
 ▶ Fetching base .env file for compose stack...
 ✓ 
 ▶ Setting environment variables in .env file for compose stack... ✓ 
 ✓ 
 ▶ Using existing docker-compose file at /opt/apps/xxxxxxxxxxx/docker-compose.yaml...  ✓ 
 ▶ Enabling enrollment proxy service in compose file... ✓ 
 ▶ latest release Docker images will be used
 ▶ Fetching latest release Docker images: 
[+] Pulling 1/1
 ✔ defguard-server Pulled                                                                                                                                             1.0s 
 ▶ Enabling VPN gateway service...
   ▷ Fetching latest gateway image...
no such service: gateway
 ▶ Adding VPN to core & generating gateway token...
no such service: core
ERROR: failed to create VPN network
```

**Version information**
- Defguard Deployment script version: v1.1.0
  - Operating system and version running the gateway: Ubuntu 22.04 LTS
  - Your browser and version: Firefox 131.0.3

**Comment by teon** [comment]
@federicochiesa few questions:
1. are you using the distribution docker & compose (which is not recommended) or official docker packages ?
2. what release are you trying to install (latest production, dev, pre-release)?

**Comment by teon** [comment]
@federicochiesa I ment what kind of "docker" installation do you have - did you install docker from Ubuntu packages or these packages: https://docs.docker.com/engine/install/ubuntu/

**Comment by t-aleksander** [comment]
@federicochiesa we've updated the script, you can try deploying it again with the newest version, it should prevent such situation from happening again. Try running the whole thing in a completely clean, new directory.

**Comment by federicochiesa** [comment]
The script now works. Thanks!
