### ISSUE TITLE
Missing enable icon one time password for MFA in profile user

### ISSUE THREAD

**Issue by djjm86** [DefGuard/defguard#838]
Hello,

I have installed Defguard Core, Gateway, and Proxy.

defguard 0.11.0
defguard-gateway 0.7.2
defguard-proxy 0.5.1

In the user profiles, I do not have the option to enable MFA One Time Password.

Please find the attached screenshots.

![2024-10-24 17_06_09-Defguard](https://github.com/user-attachments/assets/e26c27e2-6da3-4cf3-adbe-9e6b87dfba23)

![2024-10-24 17_07_32-Defguard — Mozilla Firefox](https://github.com/user-attachments/assets/449793f6-c63b-48ad-93df-c1c2636e6cab)

**Comment by teon** [comment]
@djjm86 you need to click ,Edit’ button in the top right corner on user profile 🫡
